# Generated by Django 4.2.9 on 2024-01-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('AN', 'Пользователь без авторизации'), ('CL', 'Клиент'), ('SE', 'Сервисная организация'), ('MG', 'Менеджер'), ('AD', 'Администратор')], default='AN', max_length=2, verbose_name='Роль пользователя'),
        ),
    ]
