# Generated by Django 4.2.9 on 2024-01-20 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deskbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driveaxle',
            options={'verbose_name': 'Модель ведущего моста', 'verbose_name_plural': 'Модели ведущего моста'},
        ),
        migrations.AlterModelOptions(
            name='enginemodel',
            options={'verbose_name': 'Модель двигателя', 'verbose_name_plural': 'Модели двигателя'},
        ),
        migrations.AlterModelOptions(
            name='steeringaxle',
            options={'verbose_name': 'Модель управляемого моста', 'verbose_name_plural': 'Модели управляемого моста'},
        ),
        migrations.AlterModelOptions(
            name='transmissionmodel',
            options={'verbose_name': 'Модель трансмиссии', 'verbose_name_plural': 'Модели трансмиссии'},
        ),
        migrations.AlterModelOptions(
            name='vehiclemodel',
            options={'verbose_name': 'Модель техники', 'verbose_name_plural': 'Модели техники'},
        ),
    ]
