# Generated by Django 4.2.9 on 2024-01-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number_vehicle', models.CharField(max_length=32, unique=True, verbose_name='Зав. № машины')),
                ('vehicle_model', models.CharField(max_length=128, verbose_name='Модель техники')),
                ('engine_model', models.CharField(max_length=128, verbose_name='Модель двигателя')),
                ('serial_number_of_the_engine', models.CharField(max_length=32, unique=True, verbose_name='Зав. № двигателя')),
                ('transmission_model', models.CharField(max_length=128, verbose_name='Модель трансмиссии')),
                ('serial_number_of_the_transmission', models.CharField(max_length=32, unique=True, verbose_name='Зав. № трансмиссии')),
                ('drive_axle_model', models.CharField(max_length=128, verbose_name='Модель ведущего моста')),
                ('drive_axle_serial_number', models.CharField(max_length=32, unique=True, verbose_name='Зав. № ведущего моста')),
                ('steering_axle_model', models.CharField(max_length=128, verbose_name='Модель управляемого моста')),
                ('serial_number_of_the_steered_axle', models.CharField(max_length=32, unique=True, verbose_name='Зав. № управляемого моста')),
                ('supply_contract', models.CharField(blank=True, max_length=128, null=True, verbose_name='Договор поставки №, дата')),
                ('date_shipped_from_factory', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('consignee', models.CharField(max_length=128, verbose_name='Грузополучатель (конечный потребитель)')),
                ('delivery_address', models.CharField(max_length=256, verbose_name='Адрес поставки (эксплуатации)')),
                ('equipment', models.TextField(blank=True, null=True, verbose_name='Комплектация (доп. опции)')),
                ('client', models.CharField(blank=True, max_length=128, null=True, verbose_name='Клиент')),
                ('service_company', models.CharField(max_length=128, verbose_name='Сервисная компания')),
            ],
            options={
                'verbose_name': 'Машину',
                'verbose_name_plural': 'Машины',
                'db_table': 'car',
            },
        ),
    ]
