# Generated by Django 4.2.9 on 2024-01-15 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deskbook', '0001_initial'),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='drive_axle_model',
            field=models.ForeignKey(default='Не назначено', on_delete=django.db.models.deletion.SET_DEFAULT, to='deskbook.driveaxle', verbose_name='Модель ведущего моста'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='engine_model',
            field=models.ForeignKey(default='Не назначено', on_delete=django.db.models.deletion.SET_DEFAULT, to='deskbook.enginemodel', verbose_name='Модель двигателя'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='steering_axle_model',
            field=models.ForeignKey(default='Не назначено', on_delete=django.db.models.deletion.SET_DEFAULT, to='deskbook.steeringaxle', verbose_name='Модель управляемого моста'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='transmission_model',
            field=models.ForeignKey(default='Не назначено', on_delete=django.db.models.deletion.SET_DEFAULT, to='deskbook.transmissionmodel', verbose_name='Модель трансмиссии'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='vehicle_model',
            field=models.ForeignKey(default='Не назначено', on_delete=django.db.models.deletion.SET_DEFAULT, to='deskbook.vehiclemodel', verbose_name='Модель техники'),
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_refusal', models.DateField(verbose_name='Дата отказа')),
                ('operating_hours', models.IntegerField(verbose_name='Наработка, м/час')),
                ('description_of_failure', models.TextField(blank=True, null=True, verbose_name='Описание отказа')),
                ('parts_used', models.TextField(blank=True, null=True, verbose_name='Используемые запасные части')),
                ('restore_date', models.DateField(verbose_name='Дата восстановления')),
                ('car', models.ForeignKey(default='Не назначено', on_delete=django.db.models.deletion.SET_DEFAULT, to='cars.cars', verbose_name='Машина')),
                ('failure_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deskbook.failurenode', verbose_name='Узел отказа')),
                ('recovery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deskbook.recoverymethod', verbose_name='Способ восстановления')),
                ('service_company', models.ForeignKey(default='Не назначено', on_delete=django.db.models.deletion.SET_DEFAULT, to='cars.servicecompany', verbose_name='Сервисная компания')),
            ],
            options={
                'verbose_name': 'Рекламация',
                'verbose_name_plural': 'Рекламации',
                'db_table': 'reclamation',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_maintenance', models.DateField(verbose_name='Дата проведения ТО')),
                ('operating_hours', models.IntegerField(verbose_name='Наработка, м/час')),
                ('work_order_number', models.CharField(max_length=128, unique=True, verbose_name='№ заказ-наряда')),
                ('work_order_date', models.DateField(verbose_name='Дата заказ-наряда')),
                ('car', models.ForeignKey(default='Не назначено', on_delete=django.db.models.deletion.SET_DEFAULT, to='cars.cars', verbose_name='Машина')),
                ('service_company', models.ForeignKey(default='Не назначено', on_delete=django.db.models.deletion.SET_DEFAULT, to='cars.servicecompany', verbose_name='Сервисная компания')),
                ('view_maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deskbook.viewmaintenance', verbose_name='Вид ТО')),
            ],
            options={
                'verbose_name': 'ТО',
                'verbose_name_plural': 'ТО',
                'db_table': 'maintenance',
            },
        ),
    ]
