# Generated by Django 4.2.9 on 2024-01-30 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0001_initial'),
        ('deskbook', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='cars',
            name='drive_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deskbook.driveaxle', verbose_name='Модель ведущего моста'),
        ),
        migrations.AddField(
            model_name='cars',
            name='engine_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deskbook.enginemodel', verbose_name='Модель двигателя'),
        ),
        migrations.AddField(
            model_name='cars',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AddField(
            model_name='cars',
            name='steering_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deskbook.steeringaxle', verbose_name='Модель управляемого моста'),
        ),
        migrations.AddField(
            model_name='cars',
            name='transmission_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deskbook.transmissionmodel', verbose_name='Модель трансмиссии'),
        ),
        migrations.AddField(
            model_name='cars',
            name='vehicle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deskbook.vehiclemodel', verbose_name='Модель техники'),
        ),
    ]
