# Generated by Django 4.2.9 on 2024-01-20 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_cars_drive_axle_model_alter_cars_engine_model_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ('Date_maintenance',), 'verbose_name': 'ТО', 'verbose_name_plural': 'ТО'},
        ),
        migrations.AlterModelOptions(
            name='reclamation',
            options={'ordering': ('date_of_refusal',), 'verbose_name': 'Рекламация', 'verbose_name_plural': 'Рекламации'},
        ),
    ]
