# Generated by Django 4.2.9 on 2024-02-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='drive_axle_serial_number',
            field=models.CharField(max_length=32, verbose_name='Зав. № ведущего моста'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='serial_number_of_the_engine',
            field=models.CharField(max_length=32, verbose_name='Зав. № двигателя'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='serial_number_of_the_steered_axle',
            field=models.CharField(max_length=32, verbose_name='Зав. № управляемого моста'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='serial_number_of_the_transmission',
            field=models.CharField(max_length=32, verbose_name='Зав. № трансмиссии'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='serial_number_vehicle',
            field=models.CharField(max_length=32, verbose_name='Зав. № машины'),
        ),
    ]
