# Generated by Django 4.2.9 on 2024-01-26 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_maintenance_options_alter_reclamation_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamation',
            name='car',
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='failure_node',
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='recovery_method',
        ),
        migrations.RemoveField(
            model_name='reclamation',
            name='service_company',
        ),
        migrations.AlterModelOptions(
            name='cars',
            options={'ordering': ('engine_model',), 'verbose_name': 'Машину', 'verbose_name_plural': 'Машины'},
        ),
        migrations.DeleteModel(
            name='Maintenance',
        ),
        migrations.DeleteModel(
            name='Reclamation',
        ),
    ]
