# Generated by Django 4.2.9 on 2024-02-16 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deskbook', '0001_initial'),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_maintenance', models.DateField(verbose_name='Дата проведения ТО')),
                ('operating_hours', models.IntegerField(verbose_name='Наработка, м/час')),
                ('work_order_number', models.CharField(max_length=128, verbose_name='№ заказ-наряда')),
                ('work_order_date', models.DateField(verbose_name='Дата заказ-наряда')),
                ('car', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='cars.cars', verbose_name='Машина')),
                ('service_company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='deskbook.servicecompany', verbose_name='Сервисная компания')),
                ('view_maintenance', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='deskbook.viewmaintenance', verbose_name='Вид ТО')),
            ],
            options={
                'verbose_name': 'ТО',
                'verbose_name_plural': 'ТО',
                'db_table': 'maintenance',
                'ordering': ('car',),
            },
        ),
    ]
