# Generated by Django 4.2.9 on 2024-02-11 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('cars', '0004_alter_cars_client_alter_cars_drive_axle_model_and_more'),
        ('deskbook', '0003_alter_driveaxle_options_alter_enginemodel_options_and_more'),
        ('maintenance', '0003_alter_maintenance_work_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='cars.cars', verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='service_company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='view_maintenance',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='deskbook.viewmaintenance', verbose_name='Вид ТО'),
        ),
    ]
