# Generated by Django 4.2.9 on 2024-01-26 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deskbook', '0002_alter_driveaxle_options_alter_enginemodel_options_and_more'),
        ('cars', '0004_remove_reclamation_car_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_refusal', models.DateField(verbose_name='Дата отказа')),
                ('operating_hours', models.IntegerField(verbose_name='Наработка, м/час')),
                ('description_of_failure', models.TextField(blank=True, null=True, verbose_name='Описание отказа')),
                ('parts_used', models.TextField(blank=True, null=True, verbose_name='Используемые запасные части')),
                ('restore_date', models.DateField(verbose_name='Дата восстановления')),
                ('car', models.ForeignKey(default='Не назначено', on_delete=django.db.models.deletion.SET_DEFAULT, to='cars.cars', verbose_name='Машина')),
                ('failure_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deskbook.failurenode', verbose_name='Узел отказа')),
                ('recovery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deskbook.recoverymethod', verbose_name='Способ восстановления')),
                ('service_company', models.ForeignKey(default='Не назначено', on_delete=django.db.models.deletion.SET_DEFAULT, to='cars.servicecompany', verbose_name='Сервисная компания')),
            ],
            options={
                'verbose_name': 'Рекламация',
                'verbose_name_plural': 'Рекламации',
                'db_table': 'reclamation',
                'ordering': ('car',),
            },
        ),
    ]
