# Generated by Django 4.2.9 on 2024-02-11 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('cars', '0004_alter_cars_client_alter_cars_drive_axle_model_and_more'),
        ('deskbook', '0003_alter_driveaxle_options_alter_enginemodel_options_and_more'),
        ('reclamation', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='cars.cars', verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='failure_node',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='deskbook.failurenode', verbose_name='Узел отказа'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='recovery_method',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='deskbook.recoverymethod', verbose_name='Способ восстановления'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='service_company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.servicecompany', verbose_name='Сервисная компания'),
        ),
    ]
